sudo: true
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - .eslintcache
install:
  - npm install -g codecov
script: 
  - npm run test
  - codecov
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  
